# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json

theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - name: Home
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: bookmarks
            groups:
              - links:
                  - title: ProxmoxVE Helper Scripts
                    url: https://community-scripts.github.io/ProxmoxVE/
                  - title: Router Admin Console
                    url: http://192.168.1.1

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Beelink SEi13
                url: https://proxmox.welara-turtle.ts.net
                icon: di:proxmox
              - title: UGREEN NASync DXP4800 Plus
                url: https://nas.welara-turtle.ts.net
                icon: di:proxmox
              - title: Home Assistant
                url: https://homeassistant.welara-turtle.ts.net
                icon: di:home-assistant
              - title: qBittorrent
                url: https://qbittorrent.welara-turtle.ts.net
                icon: di:qbittorrent
              - title: Pi-hole
                url: https://pi-hole.welara-turtle.ts.net/admin
                icon: di:pi-hole
              - title: Jellyfin
                url: https://jellyfin.welara-turtle.ts.net
                icon: di:jellyfin
              - title: Gitea
                url: https://gitea.welara-turtle.ts.net
                icon: di:gitea

          - type: split-column
            widgets:
              - type: dns-stats
                service: pihole-v6
                url: https://pi-hole.welara-turtle.ts.net
                password: ${PI_HOLE_PASSWORD}
                hour-format: 24h

              - type: html
                source: |
                  <div hidden>placeholder</div>

      - size: small
        widgets:
          - type: clock
            hour-format: 24h

          - type: weather
            location: Hilversum, The Netherlands
            units: metric
            hour-format: 24h

          - type: repository
            cache: 1m
            repository: mhogeveen/homelab
            pull-requests-limit: 5
            issues-limit: 3
            commits-limit: 3

          - type: repository
            cache: 1m
            repository: mhogeveen/dotfiles
            pull-requests-limit: 5
            issues-limit: 3
            commits-limit: 3

          - type: custom-api
            title: Random Fact
            cache: 1h
            url: https://uselessfacts.jsph.pl/api/v2/facts/random
            template: |
              <p class="size-h4 color-paragraph">{{ .JSON.String "text" }}</p>
