---
- name: Synchronize glance files
  when: inventory_hostname == 'glance'
  block:
    - name: Copy
      ansible.builtin.copy:
        src: glance/
        dest: /docker/glance/
        owner: root
        group: root
        mode: "0644"

- name: Synchronize pi-hole files
  when: inventory_hostname == 'pi-hole'
  block:
    - name: Copy
      ansible.builtin.copy:
        src: pi-hole/
        dest: /docker/pi-hole/
        owner: root
        group: root
        mode: "0644"

- name: Synchronize nas files
  when: inventory_hostname == 'nas'
  block:
    - name: Samba files
      ansible.builtin.copy:
        src: nas/samba/
        dest: /etc/samba/
        owner: root
        group: root
        mode: "0644"

    - name: Ugreen LEDs files
      ansible.builtin.copy:
        src: nas/ugreen-leds/
        dest: /etc/init.d/
        owner: root
        group: root
        mode: "0644"
